Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
IBMQ.save_account("..")
IBMQ.load_account()
provider = IBMQ.get_provider(hub='ibm-q')

------------------

----- stderr -----
/tmp/ipykernel_2222/1612257047.py:1: DeprecationWarning: The package qiskit.providers.ibmq is being deprecated. Please see https://ibm.biz/provider_migration_guide to get instructions on how to migrate to qiskit-ibm-provider (https://github.com/Qiskit/qiskit-ibm-provider) and qiskit-ibm-runtime (https://github.com/Qiskit/qiskit-ibm-runtime).
  IBMQ.save_account("..")
/tmp/ipykernel_2222/1612257047.py:1: DeprecationWarning: The qiskit.IBMQ entrypoint and the qiskit-ibmq-provider package (accessible from 'qiskit.providers.ibmq`) are deprecated and will be removed in a future release. Instead you should use the qiskit-ibm-provider package which is accessible from 'qiskit_ibm_provider'. You can install it with 'pip install qiskit_ibm_provider'. Just replace 'qiskit.IBMQ' with 'qiskit_ibm_provider.IBMProvider'
  IBMQ.save_account("..")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/providers/ibmq/api/session.py:278[0m, in [0;36mRetrySession.request[0;34m(self, method, url, bare, **kwargs)[0m
[1;32m    277[0m     response [38;5;241m=[39m [38;5;28msuper[39m()[38;5;241m.[39mrequest(method, final_url, headers[38;5;241m=[39mheaders, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m--> 278[0m     [43mresponse[49m[38;5;241;43m.[39;49m[43mraise_for_status[49m[43m([49m[43m)[49m
[1;32m    279[0m [38;5;28;01mexcept[39;00m RequestException [38;5;28;01mas[39;00m ex:
[1;32m    280[0m     [38;5;66;03m# Wrap the requests exceptions into a IBM Q custom one, for[39;00m
[1;32m    281[0m     [38;5;66;03m# compatibility.[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py:1021[0m, in [0;36mResponse.raise_for_status[0;34m(self)[0m
[1;32m   1020[0m [38;5;28;01mif[39;00m http_error_msg:
[0;32m-> 1021[0m     [38;5;28;01mraise[39;00m HTTPError(http_error_msg, response[38;5;241m=[39m[38;5;28mself[39m)

[0;31mHTTPError[0m: 401 Client Error: Unauthorized for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken

The above exception was the direct cause of the following exception:

[0;31mRequestsApiError[0m                          Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m IBMQ[38;5;241m.[39msave_account([38;5;124m"[39m[38;5;124m..[39m[38;5;124m"[39m)
[0;32m----> 2[0m [43mIBMQ[49m[38;5;241;43m.[39;49m[43mload_account[49m[43m([49m[43m)[49m
[1;32m      3[0m provider [38;5;241m=[39m IBMQ[38;5;241m.[39mget_provider(hub[38;5;241m=[39m[38;5;124m'[39m[38;5;124mibm-q[39m[38;5;124m'[39m)

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/providers/ibmq/ibmqfactory.py:191[0m, in [0;36mIBMQFactory.load_account[0;34m(self)[0m
[1;32m    187[0m     logger[38;5;241m.[39mwarning([38;5;124m'[39m[38;5;124mCredentials are already in use. The existing [39m[38;5;124m'[39m
[1;32m    188[0m                    [38;5;124m'[39m[38;5;124maccount in the session will be replaced.[39m[38;5;124m'[39m)
[1;32m    189[0m     [38;5;28mself[39m[38;5;241m.[39mdisable_account()
[0;32m--> 191[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_initialize_providers[49m[43m([49m[43mcredentials[49m[43m,[49m[43m [49m[43mpreferences[49m[43m)[49m
[1;32m    193[0m [38;5;66;03m# Prevent edge case where no hubs are available.[39;00m
[1;32m    194[0m providers [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mproviders()

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/providers/ibmq/ibmqfactory.py:456[0m, in [0;36mIBMQFactory._initialize_providers[0;34m(self, credentials, preferences)[0m
[1;32m    446[0m [38;5;28;01mdef[39;00m [38;5;21m_initialize_providers[39m(
[1;32m    447[0m         [38;5;28mself[39m, credentials: Credentials,
[1;32m    448[0m         preferences: Optional[Dict] [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    449[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m    450[0m [38;5;250m    [39m[38;5;124;03m"""Authenticate against IBM Quantum and populate the providers.[39;00m
[1;32m    451[0m 
[1;32m    452[0m [38;5;124;03m    Args:[39;00m
[1;32m    453[0m [38;5;124;03m        credentials: Credentials for IBM Quantum.[39;00m
[1;32m    454[0m [38;5;124;03m        preferences: Account preferences.[39;00m
[1;32m    455[0m [38;5;124;03m    """[39;00m
[0;32m--> 456[0m     auth_client [38;5;241m=[39m [43mAuthClient[49m[43m([49m[43mcredentials[49m[38;5;241;43m.[39;49m[43mtoken[49m[43m,[49m
[1;32m    457[0m [43m                             [49m[43mcredentials[49m[38;5;241;43m.[39;49m[43mbase_url[49m[43m,[49m
[1;32m    458[0m [43m                             [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcredentials[49m[38;5;241;43m.[39;49m[43mconnection_parameters[49m[43m([49m[43m)[49m[43m)[49m
[1;32m    459[0m     service_urls [38;5;241m=[39m auth_client[38;5;241m.[39mcurrent_service_urls()
[1;32m    460[0m     user_hubs [38;5;241m=[39m auth_client[38;5;241m.[39muser_hubs()

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/providers/ibmq/api/clients/auth.py:41[0m, in [0;36mAuthClient.__init__[0;34m(self, api_token, auth_url, **request_kwargs)[0m
[1;32m     38[0m [38;5;28mself[39m[38;5;241m.[39m_service_urls [38;5;241m=[39m {}  [38;5;66;03m# type: ignore[var-annotated][39;00m
[1;32m     40[0m [38;5;28mself[39m[38;5;241m.[39mauth_api [38;5;241m=[39m Api(RetrySession(auth_url, [38;5;241m*[39m[38;5;241m*[39mrequest_kwargs))
[0;32m---> 41[0m [38;5;28mself[39m[38;5;241m.[39mbase_api [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_init_service_clients[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mrequest_kwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/providers/ibmq/api/clients/auth.py:53[0m, in [0;36mAuthClient._init_service_clients[0;34m(self, **request_kwargs)[0m
[1;32m     44[0m [38;5;250m[39m[38;5;124;03m"""Initialize the clients used for communicating with the API.[39;00m
[1;32m     45[0m 
[1;32m     46[0m [38;5;124;03mArgs:[39;00m
[0;32m   (...)[0m
[1;32m     50[0m [38;5;124;03m    Client for the API server.[39;00m
[1;32m     51[0m [38;5;124;03m"""[39;00m
[1;32m     52[0m [38;5;66;03m# Request an access token.[39;00m
[0;32m---> 53[0m access_token [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_request_access_token[49m[43m([49m[43m)[49m
[1;32m     54[0m [38;5;66;03m# Use the token for the next auth server requests.[39;00m
[1;32m     55[0m [38;5;28mself[39m[38;5;241m.[39mauth_api[38;5;241m.[39msession[38;5;241m.[39maccess_token [38;5;241m=[39m access_token

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/providers/ibmq/api/clients/auth.py:75[0m, in [0;36mAuthClient._request_access_token[0;34m(self)[0m
[1;32m     65[0m [38;5;250m[39m[38;5;124;03m"""Request a new access token from the API authentication service.[39;00m
[1;32m     66[0m 
[1;32m     67[0m [38;5;124;03mReturns:[39;00m
[0;32m   (...)[0m
[1;32m     72[0m [38;5;124;03m    RequestsApiError: If the request failed.[39;00m
[1;32m     73[0m [38;5;124;03m"""[39;00m
[1;32m     74[0m [38;5;28;01mtry[39;00m:
[0;32m---> 75[0m     response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mauth_api[49m[38;5;241;43m.[39;49m[43mlogin[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mapi_token[49m[43m)[49m
[1;32m     76[0m     [38;5;28;01mreturn[39;00m response[[38;5;124m'[39m[38;5;124mid[39m[38;5;124m'[39m]
[1;32m     77[0m [38;5;28;01mexcept[39;00m RequestsApiError [38;5;28;01mas[39;00m ex:
[1;32m     78[0m     [38;5;66;03m# Get the original exception that raised.[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/providers/ibmq/api/rest/root.py:125[0m, in [0;36mApi.login[0;34m(self, api_token)[0m
[1;32m    116[0m [38;5;250m[39m[38;5;124;03m"""Login with token.[39;00m
[1;32m    117[0m 
[1;32m    118[0m [38;5;124;03mArgs:[39;00m
[0;32m   (...)[0m
[1;32m    122[0m [38;5;124;03m    JSON response.[39;00m
[1;32m    123[0m [38;5;124;03m"""[39;00m
[1;32m    124[0m url [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_url([38;5;124m'[39m[38;5;124mlogin[39m[38;5;124m'[39m)
[0;32m--> 125[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msession[49m[38;5;241;43m.[39;49m[43mpost[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mjson[49m[38;5;241;43m=[39;49m[43m{[49m[38;5;124;43m'[39;49m[38;5;124;43mapiToken[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[43mapi_token[49m[43m}[49m[43m)[49m[38;5;241m.[39mjson()

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py:637[0m, in [0;36mSession.post[0;34m(self, url, data, json, **kwargs)[0m
[1;32m    626[0m [38;5;28;01mdef[39;00m [38;5;21mpost[39m([38;5;28mself[39m, url, data[38;5;241m=[39m[38;5;28;01mNone[39;00m, json[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    627[0m [38;5;250m    [39m[38;5;124mr[39m[38;5;124;03m"""Sends a POST request. Returns :class:`Response` object.[39;00m
[1;32m    628[0m 
[1;32m    629[0m [38;5;124;03m    :param url: URL for the new :class:`Request` object.[39;00m
[0;32m   (...)[0m
[1;32m    634[0m [38;5;124;03m    :rtype: requests.Response[39;00m
[1;32m    635[0m [38;5;124;03m    """[39;00m
[0;32m--> 637[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mrequest[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mPOST[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[38;5;241;43m=[39;49m[43mdata[49m[43m,[49m[43m [49m[43mjson[49m[38;5;241;43m=[39;49m[43mjson[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/providers/ibmq/api/session.py:300[0m, in [0;36mRetrySession.request[0;34m(self, method, url, bare, **kwargs)[0m
[1;32m    297[0m         [38;5;66;03m# Modify the original message on the chained exceptions.[39;00m
[1;32m    298[0m         [38;5;28mself[39m[38;5;241m.[39m_modify_chained_exception_messages(ex)
[0;32m--> 300[0m     [38;5;28;01mraise[39;00m RequestsApiError(message, status_code) [38;5;28;01mfrom[39;00m [38;5;21;01mex[39;00m
[1;32m    302[0m [38;5;28;01mreturn[39;00m response

[0;31mRequestsApiError[0m: '401 Client Error: Unauthorized for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken. Login failed., Error code: 3446.'

